# Generated by Django 4.2.3 on 2023-09-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childinfo',
            name='age_in_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
