# Generated by Django 4.2.3 on 2023-09-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_childinfo_age_in_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='childinfo',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childinfo',
            name='birth_date',
            field=models.IntegerField(),
        ),
    ]
